version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - ./db/data:/data/db
      - ./db/initdb:/docker-entrypoint-initdb.d
    env_file:
      - ./db/qa.env
    command: --auth

  test-explorer:
    container_name: test-explorer
    # build: .
    image: eternali/test-explorer
    restart: always
    network_mode: "host"
    env_file:
      - qa.env
    # links:
    #   - mongo:mongo